name: Node CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: use node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: install
      run: yarn

    - name: install peer deps
      run: yarn add --dev eslint-config-prettier eslint-config-airbnb

    - name: lint
      run: yarn lint

    - name: test
      run: node -c index.js

    - name: remove peer deps
      run: |
        yarn remove eslint-config-prettier eslint-config-airbnb
        yarn add --peer eslint-config-prettier eslint-config-airbnb
