name: Node Publish

permissions:
  id-token: write
  contents: read

on:
  release:
    types:
      - published

jobs:
  publish-npm:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7

      - name: setup node
        uses: actions/setup-node@v7
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - name: install
        run: yarn install --frozen-lockfile

      - name: publish
        run: npm publish --access public
